img_dir: !path [!global "INTERIM_DATA_DIR", "worms", "labels", "imgs"]
mask_dir: !path [!global "INTERIM_DATA_DIR", "worms", "labels", "masks"]
checkpoint: !path [!global "MODELS_DIR", "sam_vit_h_4b8939.pth"]